import React, { useEffect } from 'react';
import { Sparkles, Trophy, Award, Gamepad2, ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import GameSelector from '../../components/GameSelector/GameSelector';
import DailyChecklist from '../../components/DailyChecklist/DailyChecklist';
import GlassCard from '../../components/ui/GlassCard';
import NeonButton from '../../components/ui/NeonButton';
import ThreeHologram from '../../components/dashboard/ThreeHologram';
import DashboardBackground3D from '../../components/dashboard/DashboardBackground3D';
import ThreeStatVisualizer from '../../components/dashboard/ThreeStatVisualizer';
import { useGameStore } from '../../store/useGameStore';
import { useAuthStore } from '../../store/useAuthStore';
import { useMatches } from '../../hooks/useMatches';
import { useStreak } from '../../hooks/useStreak';
import { getRankDetails } from '../../lib/constants';
import { GAME_CONFIGS } from '../../lib/gameConfigs';
import './Dashboard.css';

export default function Dashboard() {
  const { profile } = useAuthStore();
  const { activeGame, gameProfiles, matchHistory } = useGameStore();
  const { fetchMatches } = useMatches();
  const { fetchStreaks } = useStreak();

  useEffect(() => {
    fetchMatches();
    fetchStreaks();
  }, [activeGame]);

  const activeProfile = gameProfiles[activeGame] || { total_xp: 0, current_rank: 'Bronze I', win_rate: 0 };
  const rank = getRankDetails(activeProfile.total_xp);
  const gameConfig = GAME_CONFIGS[activeGame || 'valorant'];

  return (
    <div className="space-y-8 pb-12 hud-grid-bg relative z-10">
      <DashboardBackground3D activeGame={activeGame} />
      {/* Futuristic HUD Welcome Control Panel */}
      <div className="hud-panel hud-panel-active grid grid-cols-1 lg:grid-cols-5 overflow-hidden">
        <div className="scanlines-overlay" />
        <div className="scan-line" />
        <div className="hud-accent-bar" />
        
        {/* Tech corners decoration */}
        <div className="tech-corner-tl" />
        <div className="tech-corner-tr" />
        <div className="tech-corner-bl" />
        <div className="tech-corner-br" />

        {/* Left panel: Info & Telemetry stats */}
        <div className="lg:col-span-3 p-8 md:p-10 flex flex-col justify-between relative z-10 space-y-6">
          <div className="space-y-4">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded bg-white/5 border border-white/10 text-[10px] font-bold tracking-widest text-slate-300 font-mono">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 hud-blink-fast" />
              <span>NEXUS OS // STABLE_CHANNEL</span>
            </div>
            <h1 className="font-display font-black text-3xl md:text-4xl text-white leading-tight uppercase tracking-wide">
              Welcome, Agent <span className="text-[var(--game-accent)] neon-text-glow">{profile?.display_name || 'Player'}</span>
            </h1>
            <p className="text-sm text-slate-400 leading-relaxed font-sans">
              Synchronize matches, review weakness reports generated by Coach {activeGame === 'valorant' ? 'Ghost' : activeGame === 'cs2' ? 'Vandal' : activeGame === 'lol' ? 'Oracle' : activeGame === 'fortnite' ? 'Skye' : 'Sniper'}, and keep your daily checklist streak going.
            </p>
          </div>

          {/* Diagnostic system terminal log output */}
          <div className="bg-black/40 border border-white/5 rounded-lg p-4 font-mono text-xs space-y-1.5">
            <div className="flex justify-between text-[10px] text-white/30 border-b border-white/5 pb-1 mb-2">
              <span>SYSTEM LOGS // CORE_DIAGNOSTICS</span>
              <span className="hud-blink-slow text-cyan-400">CONNECTING...</span>
            </div>
            <div className="telemetry-log">
              <div>[<span className="success">SYSTEM</span>] Booting neural engine core... <span className="success">SUCCESS</span></div>
              <div>[<span className="accent">COACH</span>] Syncing AI telemetry data for <span className="accent">{activeGame?.toUpperCase() || 'VALORANT'}</span>... <span className="success">ONLINE</span></div>
              <div>[<span className="warning">TELEMETRY</span>] Analyzing weakness metrics... <span className="warning">READY_FOR_SYNC</span></div>
            </div>
          </div>

          <div className="pt-2 flex gap-4">
            <Link to="/coaching">
              <NeonButton className="gap-2 select-none">
                <span>LAUNCH COACHING TERMINAL</span>
                <ArrowRight className="w-4 h-4" />
              </NeonButton>
            </Link>
          </div>
        </div>

        {/* Right panel: 3D Hologram visualization */}
        <div className="lg:col-span-2 h-64 lg:h-auto min-h-[300px] border-t lg:border-t-0 lg:border-l border-white/5 bg-slate-950/20 relative overflow-hidden flex items-center justify-center">
          <ThreeHologram activeGame={activeGame} />
        </div>
      </div>

      {/* Game Selector Area */}
      <section className="space-y-4">
        <div className="flex items-center gap-3">
          <Gamepad2 className="w-5 h-5 text-[var(--game-accent)] animate-pulse" />
          <h2 className="font-display font-black text-lg text-white uppercase tracking-wider">Select Active Game Arena</h2>
        </div>
        <GameSelector />
      </section>

      {/* Checklist & Recent Matches Split Layout */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Checklist Widget */}
        <div className="lg:col-span-2">
          <DailyChecklist />
        </div>

        {/* Quick Stats overview panel styled with futuristic HUD panel */}
        <div className="hud-panel p-6 flex flex-col gap-6 relative">
          <div className="scanlines-overlay" />
          <div className="tech-corner-tl" />
          <div className="tech-corner-tr" />
          <div className="tech-corner-bl" />
          <div className="tech-corner-br" />
          <div className="hud-accent-bar" />

          <div className="border-b border-white/5 pb-4">
            <h3 className="font-display font-black text-base text-white uppercase tracking-wider">Active Telemetry</h3>
            <p className="text-xs text-slate-500 font-mono">CORE_STATUS // SYNC_ACTIVE</p>
          </div>

          <div className="space-y-4 relative z-10">
            {/* Rank Card */}
            <div className="flex items-center justify-between p-4 bg-white/5 rounded-xl border border-white/5">
              <div className="flex items-center gap-3">
                <span className="text-3xl">{rank.badge}</span>
                <div>
                  <p className="text-[10px] text-slate-400 font-mono uppercase">Current Rank</p>
                  <p className="text-sm font-bold text-white mt-0.5">{rank.currentRank}</p>
                </div>
              </div>
              <span className="text-[10px] font-bold text-[var(--game-accent)] tracking-widest font-mono bg-white/5 px-2.5 py-1 rounded">
                LVL {Math.floor(activeProfile.total_xp / 1000) + 1}
              </span>
            </div>

            {/* Wins & Stats */}
            <div className="grid grid-cols-2 gap-4">
              <div className="p-4 bg-white/5 rounded-xl border border-white/5 text-center relative overflow-hidden flex flex-col justify-between items-center min-h-[160px]">
                <p className="text-[10px] text-slate-400 font-mono uppercase tracking-wider">Win Rate</p>
                <div className="w-20 h-20 my-1 relative">
                  <ThreeStatVisualizer type="progress-ring" value={activeProfile.win_rate} activeGame={activeGame} />
                </div>
                <p className="font-display font-bold text-base text-white mt-1 font-mono">{(activeProfile.win_rate * 100).toFixed(1)}%</p>
              </div>
              <div className="p-4 bg-white/5 rounded-xl border border-white/5 text-center relative overflow-hidden flex flex-col justify-between items-center min-h-[160px]">
                <p className="text-[10px] text-slate-400 font-mono uppercase tracking-wider">XP Earned</p>
                <div className="w-20 h-20 my-1 relative">
                  <ThreeStatVisualizer type="floating-crystal" activeGame={activeGame} />
                </div>
                <p className="font-display font-bold text-base text-[var(--game-accent)] mt-1 font-mono">{activeProfile.total_xp}</p>
              </div>
            </div>

            {/* Recent Match Logs preview */}
            <div className="space-y-3">
              <p className="text-[10px] font-bold text-slate-500 uppercase tracking-widest font-mono">Recent Match Syncs</p>
              {matchHistory.length === 0 ? (
                <p className="text-xs text-slate-600 italic">No matches uploaded yet</p>
              ) : (
                <div className="space-y-2">
                  {matchHistory.slice(0, 3).map((match, idx) => (
                    <div key={idx} className="flex justify-between items-center p-3 bg-white/3 rounded-xl border border-white/5 text-xs">
                      <div className="flex items-center gap-2">
                        <span className={`w-2 h-2 rounded-full ${match.is_win ? 'bg-emerald-500 shadow-[0_0_6px_#10b981]' : 'bg-rose-500'}`} />
                        <span className="font-semibold text-slate-200">
                          {match.kills}/{match.deaths}/{match.assists}
                        </span>
                      </div>
                      <span className="text-slate-400">
                        {new Date(match.played_at).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}
                      </span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
