import React, { useEffect } from 'react';
import { Sparkles, Trophy, Award, Gamepad2, ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import GameSelector from '../../components/GameSelector/GameSelector';
import DailyChecklist from '../../components/DailyChecklist/DailyChecklist';
import GlassCard from '../../components/ui/GlassCard';
import NeonButton from '../../components/ui/NeonButton';
import { useGameStore } from '../../store/useGameStore';
import { useAuthStore } from '../../store/useAuthStore';
import { useMatches } from '../../hooks/useMatches';
import { useStreak } from '../../hooks/useStreak';
import { getRankDetails } from '../../lib/constants';
import { GAME_CONFIGS } from '../../lib/gameConfigs';

export default function Dashboard() {
  const { profile } = useAuthStore();
  const { activeGame, gameProfiles, matchHistory } = useGameStore();
  const { fetchMatches } = useMatches();
  const { fetchStreaks } = useStreak();

  useEffect(() => {
    fetchMatches();
    fetchStreaks();
  }, [activeGame]);

  const activeProfile = gameProfiles[activeGame] || { total_xp: 0, current_rank: 'Bronze I', win_rate: 0 };
  const rank = getRankDetails(activeProfile.total_xp);
  const gameConfig = GAME_CONFIGS[activeGame || 'valorant'];

  return (
    <div className="space-y-8 pb-12">
      {/* Hero Banner Section */}
      <GlassCard 
        className="w-full relative min-h-64 flex items-center p-8 md:p-12 overflow-hidden border border-white/5"
        style={{
          backgroundImage: `linear-gradient(to right, rgba(8, 8, 16, 1) 25%, rgba(8, 8, 16, 0.8) 55%, rgba(8, 8, 16, 0.3)) , url(${gameConfig?.background})`,
          backgroundSize: 'cover',
          backgroundPosition: 'center'
        }}
      >
        <div className="space-y-4 max-w-xl relative z-10">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10 text-xs font-semibold tracking-wider text-slate-300">
            <Sparkles className="w-3.5 h-3.5 text-yellow-400" />
            <span>OPERATING SYSTEM ACTIVE</span>
          </div>
          <h1 className="font-display font-black text-3xl md:text-4xl text-white leading-tight">
            Welcome back, <span className="text-[var(--game-accent)]">{profile?.display_name || 'Player'}</span>
          </h1>
          <p className="text-sm text-slate-400 leading-relaxed">
            Synchronize matches, review weakness reports generated by Coach {activeGame === 'valorant' ? 'Ghost' : activeGame === 'cs2' ? 'Vandal' : activeGame === 'lol' ? 'Oracle' : activeGame === 'fortnite' ? 'Skye' : 'Sniper'}, and keep your daily checklist streak going.
          </p>
          <div className="pt-2 flex gap-4">
            <Link to="/coaching">
              <NeonButton className="gap-2 select-none">
                <span>OPEN COACHING PANEL</span>
                <ArrowRight className="w-4 h-4" />
              </NeonButton>
            </Link>
          </div>
        </div>
      </GlassCard>

      {/* Game Selector Area */}
      <section className="space-y-4">
        <div className="flex items-center gap-3">
          <Gamepad2 className="w-5 h-5 text-[var(--game-accent)]" />
          <h2 className="font-display font-bold text-lg text-white">Select Active Game Arena</h2>
        </div>
        <GameSelector />
      </section>

      {/* Checklist & Recent Matches Split Layout */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Checklist Widget */}
        <div className="lg:col-span-2">
          <DailyChecklist />
        </div>

        {/* Quick Stats overview panel */}
        <GlassCard className="flex flex-col gap-6">
          <div className="border-b border-white/5 pb-4">
            <h3 className="font-display font-bold text-base text-white">Active Profile</h3>
            <p className="text-xs text-slate-500">Telemetry overview for current selection</p>
          </div>

          <div className="space-y-4">
            {/* Rank Card */}
            <div className="flex items-center justify-between p-4 bg-white/5 rounded-xl border border-white/5">
              <div className="flex items-center gap-3">
                <span className="text-3xl">{rank.badge}</span>
                <div>
                  <p className="text-xs text-slate-400">Current Rank</p>
                  <p className="text-sm font-bold text-white mt-0.5">{rank.currentRank}</p>
                </div>
              </div>
              <span className="text-[10px] font-bold text-[var(--game-accent)] tracking-widest font-mono">
                LVL {Math.floor(activeProfile.total_xp / 1000) + 1}
              </span>
            </div>

            {/* Wins & Stats */}
            <div className="grid grid-cols-2 gap-4">
              <div className="p-4 bg-white/5 rounded-xl border border-white/5 text-center">
                <p className="text-xs text-slate-400">Win Rate</p>
                <p className="font-display font-bold text-lg text-white mt-1">{(activeProfile.win_rate * 100).toFixed(1)}%</p>
              </div>
              <div className="p-4 bg-white/5 rounded-xl border border-white/5 text-center">
                <p className="text-xs text-slate-400">XP Earned</p>
                <p className="font-display font-bold text-lg text-[var(--game-accent)] mt-1">{activeProfile.total_xp}</p>
              </div>
            </div>

            {/* Recent Match Logs preview */}
            <div className="space-y-3">
              <p className="text-xs font-bold text-slate-500 uppercase tracking-widest">Recent Match Syncs</p>
              {matchHistory.length === 0 ? (
                <p className="text-xs text-slate-600 italic">No matches uploaded yet</p>
              ) : (
                <div className="space-y-2">
                  {matchHistory.slice(0, 3).map((match, idx) => (
                    <div key={idx} className="flex justify-between items-center p-3 bg-white/3 rounded-xl border border-white/5 text-xs">
                      <div className="flex items-center gap-2">
                        <span className={`w-2 h-2 rounded-full ${match.is_win ? 'bg-emerald-500 shadow-[0_0_6px_#10b981]' : 'bg-rose-500'}`} />
                        <span className="font-semibold text-slate-200">
                          {match.kills}/{match.deaths}/{match.assists}
                        </span>
                      </div>
                      <span className="text-slate-400">
                        {new Date(match.played_at).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}
                      </span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        </GlassCard>
      </div>
    </div>
  );
}
