import React, { useEffect, useState, useRef } from 'react';
import { Sparkles, Trophy, Award, Gamepad2, ArrowRight, Maximize2, X, RotateCw, ChevronDown, ChevronUp } from 'lucide-react';
import { Link } from 'react-router-dom';
import GameSelector from '../../components/GameSelector/GameSelector';
import DailyChecklist from '../../components/DailyChecklist/DailyChecklist';
import GlassCard from '../../components/ui/GlassCard';
import NeonButton from '../../components/ui/NeonButton';
import ThreeHologram from '../../components/dashboard/ThreeHologram';
import DashboardBackground3D from '../../components/dashboard/DashboardBackground3D';
import ThreeStatVisualizer from '../../components/dashboard/ThreeStatVisualizer';
import { useGameStore } from '../../store/useGameStore';
import { useAuthStore } from '../../store/useAuthStore';
import { useUIStore } from '../../store/useUIStore';
import { useMatches } from '../../hooks/useMatches';
import { useStreak } from '../../hooks/useStreak';
import { getRankDetails } from '../../lib/constants';
import { GAME_CONFIGS } from '../../lib/gameConfigs';
import { playSynthSound } from '../../lib/sound';
import './Dashboard.css';

export default function Dashboard() {
  const { profile } = useAuthStore();
  const { activeGame, gameProfiles, matchHistory } = useGameStore();
  const { fetchMatches } = useMatches();
  const { fetchStreaks } = useStreak();
  const { setNavbarCollapsed, isHoloFullscreen, setIsHoloFullscreen } = useUIStore();

  const [autoRotate, setAutoRotate] = useState(true);
  const [showModalControls, setShowModalControls] = useState(true);
  const modalControlsTimeoutRef = useRef(null);

  const resetModalControlsTimeout = () => {
    setShowModalControls(true);
    if (modalControlsTimeoutRef.current) {
      clearTimeout(modalControlsTimeoutRef.current);
    }
    modalControlsTimeoutRef.current = setTimeout(() => {
      setShowModalControls(false);
    }, 2500);
  };

  useEffect(() => {
    return () => {
      if (modalControlsTimeoutRef.current) {
        clearTimeout(modalControlsTimeoutRef.current);
      }
    };
  }, []);

  useEffect(() => {
    fetchMatches();
    fetchStreaks();
  }, [activeGame]);

  useEffect(() => {
    setNavbarCollapsed(isHoloFullscreen);
    return () => setNavbarCollapsed(false);
  }, [isHoloFullscreen, setNavbarCollapsed]);

  const activeProfile = gameProfiles[activeGame] || { total_xp: 0, current_rank: 'Bronze I', win_rate: 0 };
  const rank = getRankDetails(activeProfile.total_xp);
  const gameConfig = GAME_CONFIGS[activeGame || 'valorant'];

  return (
    <div className="space-y-8 pb-12 hud-grid-bg relative z-10">
      <DashboardBackground3D activeGame={activeGame} />
      {/* Futuristic HUD Welcome Control Panel */}
      <div className="hud-panel hud-panel-active grid grid-cols-1 lg:grid-cols-5 overflow-hidden">
        <div className="scanlines-overlay" />
        <div className="scan-line" />
        <div className="hud-accent-bar" />
        
        {/* Tech corners decoration */}
        <div className="tech-corner-tl" />
        <div className="tech-corner-tr" />
        <div className="tech-corner-bl" />
        <div className="tech-corner-br" />

        {/* Left panel: Info & Telemetry stats */}
        <div className="lg:col-span-3 p-8 md:p-10 flex flex-col justify-between relative z-10 space-y-6">
          <div className="flex items-start gap-5">
            {profile?.avatar_url && (
              <img 
                src={profile.avatar_url} 
                alt="Agent Avatar" 
                className="w-16 h-16 rounded-2xl object-cover border-2 border-[var(--game-accent)] shadow-[0_0_15px_var(--game-glow)] select-none shrink-0" 
              />
            )}
            <div className="space-y-4 flex-1">
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded bg-white/5 border border-white/10 text-[10px] font-bold tracking-widest text-slate-300 font-mono">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 hud-blink-fast" />
                <span>NEXUS OS // STABLE_CHANNEL</span>
              </div>
              <h1 className="font-display font-black text-3xl md:text-4xl text-white leading-tight uppercase tracking-wide">
                Welcome, Agent <span className="text-[var(--game-accent)] neon-text-glow">{profile?.display_name || 'Player'}</span>
              </h1>
              <p className="text-sm text-slate-400 leading-relaxed font-sans">
                Synchronize matches, review weakness reports generated by Coach {activeGame === 'valorant' ? 'Ghost' : activeGame === 'cs2' ? 'Vandal' : activeGame === 'lol' ? 'Oracle' : activeGame === 'fortnite' ? 'Skye' : 'Sniper'}, and keep your daily checklist streak going.
              </p>
            </div>
          </div>

          {/* Diagnostic system terminal log output */}
          <div className="bg-black/40 border border-white/5 rounded-lg p-4 font-mono text-xs space-y-1.5">
            <div className="flex justify-between text-[10px] text-white/30 border-b border-white/5 pb-1 mb-2">
              <span>SYSTEM LOGS // CORE_DIAGNOSTICS</span>
              <span className="hud-blink-slow text-cyan-400">CONNECTING...</span>
            </div>
            <div className="telemetry-log">
              <div>[<span className="success">SYSTEM</span>] Booting neural engine core... <span className="success">SUCCESS</span></div>
              <div>[<span className="accent">COACH</span>] Syncing AI telemetry data for <span className="accent">{activeGame?.toUpperCase() || 'VALORANT'}</span>... <span className="success">ONLINE</span></div>
              <div>[<span className="warning">TELEMETRY</span>] Analyzing weakness metrics... <span className="warning">READY_FOR_SYNC</span></div>
            </div>
          </div>

          <div className="pt-2 flex gap-4">
            <Link 
              to="/coaching"
              onMouseEnter={() => playSynthSound('hover')}
              onClick={() => playSynthSound('transition')}
            >
              <NeonButton className="gap-2 select-none">
                <span>LAUNCH NEXUS AI TERMINAL</span>
                <ArrowRight className="w-4 h-4" />
              </NeonButton>
            </Link>
          </div>
        </div>

        {/* Right panel: 3D Hologram visualization */}
        <div className="lg:col-span-2 h-64 lg:h-auto min-h-[300px] border-t lg:border-t-0 lg:border-l border-white/5 bg-slate-950/20 relative overflow-hidden flex items-center justify-center group/holo">
          <ThreeHologram activeGame={activeGame} />
          
          {/* Maximize Button */}
          <button
            onClick={() => {
              playSynthSound('click');
              setIsHoloFullscreen(true);
              resetModalControlsTimeout();
            }}
            className="absolute top-4 right-4 p-2 bg-black/60 border border-white/5 hover:border-[var(--game-accent)] hover:text-white rounded-lg text-slate-400 transition-all duration-300 opacity-0 group-hover/holo:opacity-100 z-20 shadow-lg backdrop-blur-sm flex items-center gap-1.5 text-[10px] font-mono tracking-wider"
          >
            <Maximize2 className="w-3.5 h-3.5" />
            <span>360° ORBIT</span>
          </button>
        </div>
      </div>

      {/* Game Selector Area */}
      <section className="space-y-4">
        <div className="flex items-center gap-3">
          <Gamepad2 className="w-5 h-5 text-[var(--game-accent)] animate-pulse" />
          <h2 className="font-display font-black text-lg text-white uppercase tracking-wider">Select Active Game Arena</h2>
        </div>
        <GameSelector />
      </section>

      {/* Checklist & Recent Matches Split Layout */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Checklist Widget */}
        <div className="lg:col-span-2">
          <DailyChecklist />
        </div>

        {/* Quick Stats overview panel styled with futuristic HUD panel */}
        <div className="hud-panel p-6 flex flex-col gap-6 relative">
          <div className="scanlines-overlay" />
          <div className="tech-corner-tl" />
          <div className="tech-corner-tr" />
          <div className="tech-corner-bl" />
          <div className="tech-corner-br" />
          <div className="hud-accent-bar" />

          <div className="border-b border-white/5 pb-4">
            <h3 className="font-display font-black text-base text-white uppercase tracking-wider">Active Telemetry</h3>
            <p className="text-xs text-slate-500 font-mono">CORE_STATUS // SYNC_ACTIVE</p>
          </div>

          <div className="space-y-4 relative z-10">
            {/* Rank Card */}
            <div className="flex items-center justify-between p-4 bg-white/5 rounded-xl border border-white/5">
              <div className="flex items-center gap-3">
                <span className="text-3xl">{rank.badge}</span>
                <div>
                  <p className="text-[10px] text-slate-400 font-mono uppercase">Current Rank</p>
                  <p className="text-sm font-bold text-white mt-0.5">{rank.currentRank}</p>
                </div>
              </div>
              <span className="text-[10px] font-bold text-[var(--game-accent)] tracking-widest font-mono bg-white/5 px-2.5 py-1 rounded">
                LVL {Math.floor(activeProfile.total_xp / 1000) + 1}
              </span>
            </div>

            {/* Wins & Stats */}
            <div className="grid grid-cols-2 gap-4">
              <div className="p-4 bg-white/5 rounded-xl border border-white/5 text-center relative overflow-hidden flex flex-col justify-between items-center min-h-[160px]">
                <p className="text-[10px] text-slate-400 font-mono uppercase tracking-wider">Win Rate</p>
                <div className="w-20 h-20 my-1 relative">
                  <ThreeStatVisualizer type="progress-ring" value={activeProfile.win_rate} activeGame={activeGame} />
                </div>
                <p className="font-display font-bold text-base text-white mt-1 font-mono">{(activeProfile.win_rate * 100).toFixed(1)}%</p>
              </div>
              <div className="p-4 bg-white/5 rounded-xl border border-white/5 text-center relative overflow-hidden flex flex-col justify-between items-center min-h-[160px]">
                <p className="text-[10px] text-slate-400 font-mono uppercase tracking-wider">XP Earned</p>
                <div className="w-20 h-20 my-1 relative">
                  <ThreeStatVisualizer type="floating-crystal" activeGame={activeGame} />
                </div>
                <p className="font-display font-bold text-base text-[var(--game-accent)] mt-1 font-mono">{activeProfile.total_xp}</p>
              </div>
            </div>

            {/* Recent Match Logs preview */}
            <div className="space-y-3">
              <p className="text-[10px] font-bold text-slate-500 uppercase tracking-widest font-mono">Recent Match Syncs</p>
              {matchHistory.length === 0 ? (
                <p className="text-xs text-slate-600 italic">No matches uploaded yet</p>
              ) : (
                <div className="space-y-2">
                  {matchHistory.slice(0, 3).map((match, idx) => (
                    <div 
                      key={idx} 
                      onMouseEnter={() => playSynthSound('hover')}
                      onClick={() => playSynthSound('click')}
                      className="flex justify-between items-center p-3 bg-white/3 rounded-xl border border-white/5 text-xs hover:border-[var(--game-accent)] hover:bg-white/5 cursor-pointer transition-all duration-200"
                    >
                      <div className="flex items-center gap-2">
                        <span className={`w-2 h-2 rounded-full ${match.is_win ? 'bg-emerald-500 shadow-[0_0_6px_#10b981]' : 'bg-rose-500'}`} />
                        <span className="font-semibold text-slate-200">
                          {match.kills}/{match.deaths}/{match.assists}
                        </span>
                      </div>
                      <span className="text-slate-400">
                        {new Date(match.played_at).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}
                      </span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
      {/* 3D Hologram Fullscreen Modal */}
      {isHoloFullscreen && (
        <div 
          onMouseMove={resetModalControlsTimeout}
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 backdrop-blur-md animate-fade-in"
        >
          {/* Top Dropdown / Collapse Toggle Tab */}
          <button
            onClick={() => {
              playSynthSound('click');
              setShowModalControls(!showModalControls);
            }}
            className="absolute top-0 left-1/2 -translate-x-1/2 z-[70] px-5 py-1.5 bg-black/80 border-b border-x border-white/10 rounded-b-xl text-slate-400 hover:text-[var(--game-accent)] hover:shadow-[0_0_10px_var(--game-glow)] transition-all flex items-center justify-center pointer-events-auto shadow-md"
            title={showModalControls ? "Hide controls" : "Show controls"}
          >
            {showModalControls ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4 animate-bounce" />}
          </button>

          {/* Neon corner decals */}
          <div className={`absolute inset-4 md:inset-10 border border-white/5 pointer-events-none rounded-2xl transition-all duration-500 ${showModalControls ? 'opacity-100' : 'opacity-0 scale-95'}`}>
            <div className="absolute top-4 left-6 font-mono text-[10px] text-white/50 tracking-[0.2em] uppercase hidden md:block">
              // TELEMETRY VIEWPORT DIRECTORY [360° DETAILED ORBIT]
            </div>
            <div className="absolute bottom-4 left-6 font-mono text-[10px] text-[var(--game-accent)] tracking-[0.15em] uppercase hidden md:block">
              SYSTEM LEVEL: FULL SCREEN INSPECTION NODE
            </div>
            <div className="absolute bottom-4 right-6 font-mono text-[10px] text-emerald-400 tracking-[0.1em] uppercase flex items-center gap-2 hidden md:flex">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-ping" />
              ORBIT_SYNC: COMPLETED
            </div>
          </div>

          {/* Controls Bar */}
          <div className={`absolute top-6 right-6 md:top-8 md:right-8 z-[60] flex items-center gap-2 md:gap-4 transition-all duration-500 ${showModalControls ? 'opacity-100 translate-y-0' : 'opacity-0 -translate-y-4 pointer-events-none'}`}>
            <button
              onClick={() => {
                playSynthSound('click');
                setAutoRotate(!autoRotate);
              }}
              className={`flex items-center gap-2 px-3 py-1.5 rounded-lg border text-xs font-mono tracking-widest uppercase transition-all duration-200 ${
                autoRotate
                  ? 'bg-[var(--game-accent)]/10 border-[var(--game-accent)] text-[var(--game-accent)] shadow-[0_0_10px_var(--game-glow)]'
                  : 'bg-black/40 border-white/10 text-slate-400 hover:text-white hover:border-slate-500'
              }`}
            >
              <RotateCw className={`w-3.5 h-3.5 ${autoRotate ? 'animate-spin' : ''}`} style={{ animationDuration: '6s' }} />
              <span>{autoRotate ? 'AUTO_ROTATION: ON' : 'AUTO_ROTATION: OFF'}</span>
            </button>

            <button
              onClick={() => {
                playSynthSound('click');
                setIsHoloFullscreen(false);
              }}
              className="p-2 bg-black/40 border border-white/10 rounded-lg text-slate-400 hover:text-white hover:border-slate-500 transition-all duration-200"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          {/* Heavy Orbiting Hologram Viewer */}
          <div className="w-[85vw] h-[85vh] relative flex items-center justify-center">
            <ThreeHologram activeGame={activeGame} isFullscreen={true} autoRotate={autoRotate} />
            
            {/* Interactive instructions */}
            <div className={`absolute bottom-12 left-1/2 -translate-x-1/2 px-4 py-2 bg-black/60 border border-white/5 rounded-xl text-center pointer-events-none select-none z-[60] backdrop-blur-sm transition-all duration-500 ${showModalControls ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-4 pointer-events-none'}`}>
              <p className="text-[10px] font-mono text-slate-400 tracking-widest uppercase">// CLICK AND DRAG MODEL TO INSPECT IN 360 DEGREES //</p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
